name: Generate Pac-Man Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pac-Man Animation
        uses: Platane/snk@v3
        with:
          github_user_name: FeKiModesto
          inputs: |
            .github/snk-assets/pacman.svg?color_snake=pacman
            .github/snk-assets/ghost.svg?color_ghost=ghost
            .github/snk-assets/fruit.svg?color_fruit=fruit
          outputs: |
            dist/pacman.svg
            dist/pacman-dark.svg?palette=github-dark

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/*.svg
          git commit -m "feat: atualiza animação Pac-Man" || echo "Sem mudanças para commitar"
          git push origin main || echo "Sem mudanças para commitar"
