name: Generate Pac-Man Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: FeKiModesto
          outputs: |
            dist/pacman.svg
            dist/pacman-dark.svg?palette=github-dark

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/*.svg
          git commit -m "feat: atualiza animação Pac-Man" || echo "Sem mudanças para commitar"
          git push origin main || echo "Sem mudanças para commitar"
